{"id":428,"details":"\n  \n  \u003ctable\u003e\n    \u003ctr\u003e\n      \u003ctd\u003eRegion\u003c/td\u003e\n\u003ctd\u003eNouvelle-Aquitaine\u003c/td\u003e\n    \u003c/tr\u003e\n    \u003ctr\u003e\n\u003ctd\u003eDepartment\u003c/td\u003e\n\u003ctd\u003eDordogne\u003c/td\u003e\n\u003c/tr\u003e\n    \n    \u003ctr\u003e\n\u003ctd\u003eReason of Infection\u003c/td\u003e\n\u003ctd\u003evisit to Italy\u003c/td\u003e\n\u003c/tr\u003e\n  \u003c/table\u003e\n  ","patient":"Male Patient From Nouvelle Aquitaine, Dordogne","source":"unknown_source","status":"in_hospital","confirmed_at":"2020-03-06T00:00:00.000Z","created_at":"2020-03-16T10:12:53.136Z","updated_at":"2020-03-16T10:42:23.372Z","infected_by":"unknown_infection","number":154,"urls":["https://github.com/lperez31/coronavirus-france-dataset"],"recovered_at":null,"gender":"male","age":0,"nationality":"unidentified_nationality","symptomatic_at":null,"slug":"france-case-154-male-patient-from-nouvelle-aquitaine-dordogne","suggested_url":"france-case-154-male-patient-from-nouvelle-aquitaine-dordogne","hospital_stay_length_in_days":null,"days_from_symptoms_to_confirmation":null,"without_symptoms":false,"reporting_country":"fr"}