{"id":599,"details":"\n  \n  \u003ctable\u003e\n    \u003ctr\u003e\n      \u003ctd\u003eRegion\u003c/td\u003e\n\u003ctd\u003eProvence-Alpes-CÌ«te d'Azur\u003c/td\u003e\n    \u003c/tr\u003e\n    \u003ctr\u003e\n\u003ctd\u003eDepartment\u003c/td\u003e\n\u003ctd\u003eVar\u003c/td\u003e\n\u003c/tr\u003e\n    \u003ctr\u003e\n\u003ctd\u003eCity\u003c/td\u003e\n\u003ctd\u003eSix-Four-les-Plages\u003c/td\u003e\n\u003c/tr\u003e\n    \u003ctr\u003e\n\u003ctd\u003eReason of Infection\u003c/td\u003e\n\u003ctd\u003evisit to Lombardy\u003c/td\u003e\n\u003c/tr\u003e\n  \u003c/table\u003e\n  ","patient":"Female Patient From Provence Alpes Cì«Te D'azur, Var, Six Four Les Plages","source":"unknown_source","status":"in_hospital","confirmed_at":"2020-03-06T00:00:00.000Z","created_at":"2020-03-16T10:12:57.198Z","updated_at":"2020-03-16T10:42:26.101Z","infected_by":"unknown_infection","number":325,"urls":["https://github.com/lperez31/coronavirus-france-dataset"],"recovered_at":null,"gender":"female","age":0,"nationality":"unidentified_nationality","symptomatic_at":null,"slug":"france-case-325-female-patient-from-provence-alpes-ci-te-d-azur-var-six-four-les-plages","suggested_url":"france-case-325-female-patient-from-provence-alpes-ci-te-d-azur-var-six-four-les-plages","hospital_stay_length_in_days":null,"days_from_symptoms_to_confirmation":null,"without_symptoms":false,"reporting_country":"fr"}